### ISSUE TITLE
Action is not using existing workflow created in codemagic

### ISSUE THREAD

**Issue by SegunRova** [codemagic-ci-cd/trigger-codemagic-workflow-action#8]
I'm using the action to trigger codemagic on repository dispatch.

1. I have created the workflow in codemagice and applied the necessary configuration (I executed a manual build and it was successful)
2. I have specified the following in my actions

-           app-id: <MY-APPLICATION-ID>
-           workflow-id: <MY-WORKFLOW-ID> (I'm using the name of the workflow I created above)
-           token: ${{ secrets.CODEMAGIC_API_TOKEN }}

However, when the action is triggered it does not use the existiong workflow created above, it tries to create a new one with a suffix _file_  in the name, this makes codemagic to fail with error `workflow not found`.

Please what I'm i doing wrong.

**Comment by icarusdust** [comment]
Hi @SegunRova, I just gave it a try and it worked as expected. Please check if you are following the same steps as I did:

1. Placed the following configuration in `.github/workflows/main.yml`:

```
on: push

jobs:
  trigger-codemagic-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Codemagic build
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          app-id: <MY-APPLICATION-ID>
          workflow-id: <MY-WORKFLOW-ID>
          token: ${{ secrets.CODEMAGIC_API_TOKEN }}
```
 2. Entered   `app-id`: Can be found in the tab URL (https://codemagic.io/app/MY_APP_ID/build/MY_BUILD_ID), `workflow-id`: If working with codemagic.yaml, then it can be found in YAML:
```
workflows:
    ios-workflow: => THIS IS WORKFLOW_ID
      name: ios_workflow
      instance_type: mac_mini_m2
```
If working with the workflow editor, it is in the tab url (https://codemagic.io/app/APP_ID/workflow/WORKFLOW_ID/settings)
and `token`: Can be found in Teams > Personal Account > Integrations > Codemagic API

3. Merged a pull request, then the given workflow got triggered.

**Comment by SegunRova** [comment]
Hi @icarusdust , thank you for your response.
yes I'm following the steps excepts that the file is not named main.yml, below is what my configuration file looks like

```
name: Integration test

# This workflow is triggered on pushes to the repository.
on:
  repository_dispatch:
    types: [go-integration-test, java-integration-test]
    
jobs:
  services_job:
    name: integration-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: check out to repository
        uses: actions/checkout@v3
        with:
          repository: roava/app
          token: ${{ secrets.PAT }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

      - name: Trigger Codemagic build
        uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v2.0.0
        with:
          app-id: <MY-APPLICATION-ID>
          workflow-id: ${{ github.event.client_payload.name }} # this resolves to the name of the workflow i already created in codemagine i.e ms.test
          branch: 'develop'
          token: ${{ secrets.CODEMAGIC_API_TOKEN }}
```
